### ISSUE TITLE
Duplicates generated into `bin' directory

### ISSUE THREAD

**Issue by Alexander-Shukaev** [ascodt-users/ascodt-nightly#5]
It seems strange to me that when I click `Build classes` button, `src` directory gets replicated in `bin` directory, i.e. the whole tree gets copied from `src` to `bin`. Is that really necessary?

**Comment by atanasoa** [comment]
i get the cpp files inside. I look on the issue

**Comment by atanasoa** [comment]
I setup inclusion and exclusion patterns for the building of the project. This should now be good for newly created projects or if you clean your bin folder and rebuil
