### ISSUE TITLE
Component does not appear in the `Available components' view

### ISSUE THREAD

**Issue by Alexander-Shukaev** [ascodt-users/ascodt-nightly#6]
The problem with newly created components not appearing in the `Available components` view still remains by now as I can observe. Restart of the plugin is needed so that the problem goes away. Neither `Build SIDL` nor `Build classes` do not influence on it. Furthermore, only the first newly created component in a project is not shown upon creation. As soon as we restart and begin creating other components, they are shown immediately without restart.

**Comment by atanasoa** [comment]
I tested with empy project and one component. This looks fine! Can you pass by after the exams. We can see what happens
