### ISSUE TITLE
A stub for global CMakeLists.txt generation

### ISSUE THREAD

**Issue by Alexander-Shukaev** [ascodt-users/ascodt-nightly#7]
I would need something similar to the `CreateCxxBuildScripts` class. This is listener class, i.e. as far as I understand it's instantiated somewhere and then put into somewhere, where it's overridden methods are called, when certain nodes are encountered. All we need here is the same kind of class, but the one which would override methods that are called not for each component, but for the whole project.

**Comment by atanasoa** [comment]
I commited a new class CreateGlobalBuildScripts in the compiler backend. The class is already invoked by the SIDLBuilder genateBuildScripts and Compiler.java . You need to implement a template and uncomment the code in openOutputStreams and closeOutputStreams and set the correct paths to your template file and destination.
